EmailVerify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('course/', include('course.urls')),
    path('', include('post.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post import views


urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('post/', views.PostListView.as_view(), name='post'),
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='detail'),

    path('cmt/<slug:slug>', views.CommentView.as_view(), name='cmt'),
    path('reply/<int:pk>', views.ReplyView.as_view(), name='reply'),

    path('robots.txt/', views.RobotsView.as_view()),
]

post/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


STATUS = (
    ('active', 'active'),
    ('inactive', 'inactive')
)


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=160)
    slug = models.SlugField(unique=True)
    image = models.FileField()
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, choices=STATUS, default="inactive")


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title.replace("đ", "d"))
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_query_name="tagPost")
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, choices=STATUS, default="inactive")

    def __str__(self):
        return self.comment


class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, choices=STATUS, default="inactive")



    def __str__(self):
        return self.reply

post/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView

from post.models import Post, Comment, Reply


class HomeView(ListView):
    model = Post
    template_name = "home-page.html"


class PostListView(ListView):
    paginate_by = 1
    model = Post
    template_name = "post/blog.html"


class PostDetailView(DetailView):
    model = Post
    template_name = "post/detail.html"

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        _slug = self.kwargs['slug']
        _post = Post.objects.get(slug=_slug)
        context['comments'] = Comment.objects.filter(post=_post, status="active").order_by("-pk")
        context['related_post'] = Post.objects.filter(category=_post.category).exclude(slug=_slug)
        return context

class RobotsView(TemplateView):
    template_name = "robots.txt"


class CommentView(View):
    def post(self, request, **kwargs):
        _slug = self.kwargs["slug"]
        _post = Post.objects.get(slug=_slug)
        cmt = request.POST["comment"]
        Comment.objects.create(
            post = _post,
            user = request.user,
            comment = cmt
        )
        messages.info(request, "Chúng tôi đã nhận được comment của bạn và đang ở trạng thái chờ duyệt...")
        return redirect(reverse_lazy("detail", kwargs={'slug': _slug}))


class ReplyView(View):
    def post(self, request, **kwargs):
        _pk = self.kwargs['pk']
        _cmt = Comment.objects.get(pk=_pk)
        _post = Post.objects.get(tagPost__comment=_cmt)
        reply = request.POST['replyCmt']

        Reply.objects.create(
            comment = _cmt,
            user = request.user,
            reply = reply
        )
        messages.warning(request, "Chúng tôi đã nhận được trả lời của bạn và đang ở trạng thái chờ duyệt...")
        return redirect(reverse_lazy("detail", kwargs={'slug': _post.slug}))

templates/post/blog.html
{% extends 'base.html' %}
{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">
        <!--Section: Cards-->
        <section class="pt-5">

            {% for post in page_obj %}
            <!--Grid row-->
            <div class="row wow fadeIn">
                <!--Grid column-->
                <div class="col-lg-5 col-xl-4 mb-4">
                    <!--Featured image-->
                    <div class="card">
                        <div class="card-body">
                            <img src="/media/{{post.image}}" alt="" width="100%">
                        </div>
                    </div>
                </div>
                <!--Grid column-->
                <div class="col-lg-7 col-xl-7 ml-xl-4 mb-4">
                    <h3 class="mb-3 font-weight-bold dark-grey-text">
                        <strong>{{post.title}}</strong>
                    </h3>
                    <p class="grey-text">{{post.description}}</p>
                    <p>
                        <strong>{{post.created_at}}</strong>
                    </p>
                    <a href="{% url 'detail' post.slug %}"
                       class="btn btn-primary btn-md">Read more
                        <i class="fas fa-play ml-2"></i>
                    </a>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
            {% endfor %}
            <hr class="mb-5">

            <!--Pagination-->
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">

                    <!--Arrow left-->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}


                    <li class="page-item active">
                        <a class="page-link" href="#">{{ page_obj.number }}
                        </a>
                    </li>

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
            <!--Pagination-->
        </section>
        <!--Section: Cards-->
    </div>
</main>
<!--Main layout-->
{% endblock %}

templates/post/detail.html
{% extends 'base.html' %}
{% block title %}{{object.title}}{% endblock %}
{% block canonical %}{{ request.path }}{% endblock %}
{% block description %}{{object.description}}{% endblock %}

{% block head %}
<link rel="canonical" href="http://127.0.0.1:8000/{{object.slug}}">

<!--openGarp Facebook-->
<meta property="og:title" content="{{object.title}}">
<meta property="og:description" content="{{object.description}}">
<meta property="og:type" content="article">
<meta property="og:url" content="http://127.0.0.1:8000/{{ request.path }}">
<meta property="og:image" content="http://127.0.0.1:8000/media/{{object.image}}">

<!--Twitter-->
<meta name="twitter:title" content="{{object.title}}">
<meta name="twitter:description" content="{{object.description}}">
<meta name="twitter:image" content="http://127.0.0.1:8000/media/{{object.image}}">
<meta name="twitter:card" content="summary">
{% endblock %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">

        <!--Section: Post-->
        <section class="mt-4">

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Featured Image-->
                    <div class="card mb-4 wow fadeIn">

                        <img src="/media/{{object.image}}" class="img-fluid" alt="">

                    </div>
                    <!--/.Featured Image-->

                    <!--Card Content-->
                    <div class="card mb-4 wow fadeIn">
                        <!--Card content-->
                        <div class="card-body">
                            <p class="h1 my-4" style="font-size: 1.8rem">{{ object.title }}</p>
                            <p class="">{{ object.created_at }}</p>
                            <blockquote class="blockquote">
                                <p class="mb-0">{{ object.description }}</p>
                            </blockquote>
                            <p>{{object.body|safe}}</p>
                        </div>
                    </div>
                    <!--/.Card-->

                    <!--Reply-->
                    {% if user.is_authenticated %}
                    <div class="card mb-3 wow fadeIn">
                        <div class="card-header font-weight-bold text-uppercase">ý kiến của bạn</div>
                        <div class="card-body">

                            <!-- Default form reply -->
                            <form method="post" action="{% url 'cmt' object.slug %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <textarea class="form-control" name="comment" rows="5"></textarea>
                                </div>
                                <div class="text-center mt-4">
                                    <button class="btn btn-info btn-md" type="submit">Post</button>
                                </div>
                            </form>
                            <!-- Default form reply -->
                        </div>
                    </div>
                    {% else %}
                    <hr>
                    <a href="{% url 'login' %}" class="font-weight-bold">Login to Comment</a>
                    <hr>
                    {% endif %}
                    <!--/.Reply-->

                    <!--Comments-->
                    {% if comments %}
                    <div class="card card-comments mb-3 wow fadeIn">
                        <div class="card-header font-weight-bold">{{ comments.count }} comment{{ comments|pluralize }}
                        </div>
                        <div class="card-body">
                            {% for cmt in comments %}
                            <div class="media d-block d-md-flex mt-4">
                                {% if cmt.user.tag.avatar %}
                                <img class="d-flex mb-3 mx-auto "
                                     src="/media/{{ cmt.user.tagUser.avatar }}"
                                     alt="Generic placeholder image">
                                {% else %}
                                <img class="d-flex mb-3 mx-auto "
                                     src="/media/default-avatar.jpg"
                                     alt="Generic placeholder image">
                                {% endif %}
                                <div class="media-body text-center text-md-left ml-md-3 ml-0">
                                    <h5 class="mt-0 font-weight-bold">{{ cmt.user.username }} -- {{ cmt.created_at }}
                                        <a href="" class="pull-right">
                                            <i class="fas fa-reply" onclick="ReplyCmt({{cmt.pk}})"></i>
                                        </a>
                                    </h5>{{ cmt.comment }}
                                    <form action="{% url 'reply' cmt.pk %}" method="post">
                                        {% csrf_token %}
                                        <p id="showForm_{{cmt.pk}}"></p>
                                    </form>

                                    {% if cmt.reply_set.all %}
                                    {% for reply in cmt.reply_set.all %}
                                    {% if reply.status == 'active' %}
                                    <div class="media d-block d-md-flex mt-3">
                                        {% if reply.user.tagUser.avatar %}
                                        <img class="d-flex mb-3 mx-auto "
                                             src="/media/{{ user.tagUser.avatar }}"
                                             alt="Generic placeholder image">
                                        {% else %}
                                        <img class="d-flex mb-3 mx-auto "
                                             src="/media/default-avatar.jpg"
                                             alt="Generic placeholder image">
                                        {% endif %}
                                        <div class="media-body text-center text-md-left ml-md-3 ml-0">
                                            <h5 class="mt-0 font-weight-bold">{{ reply.user.username }}-- {{cmt.created_at }}
                                            </h5>
                                            {{ reply.reply }}
                                        </div>
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                    {% endif %}

                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <!--/.Comments-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">
                    {% if related_post %}

                    <!--Card-->
                    <div class="card mb-4 wow fadeIn">

                        <div class="card-header">Bài viết liên quan</div>

                        <!--Card content-->
                        <div class="card-body">

                            <ul class="list-unstyled">
                                {% for rpost in related_post %}
                                <li class="media">
                                    <img class="d-flex mr-3"
                                         src="/media/{{ rpost.image }}"
                                         alt="Generic placeholder image" width="30%">
                                    <div class="media-body">
                                        <a href="{% url 'detail' rpost.slug %}">
                                            <h5 class="mt-0 mb-1 font-weight-bold">{{ rpost.title}}</h5>
                                        </a>
                                        {{rpost.description|truncatechars:70}}
                                    </div>
                                </li>
                                <hr>
                                {% endfor %}
                            </ul>

                        </div>

                    </div>
                    <!--/.Card-->
                    {% endif %}

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </section>
        <!--Section: Post-->

    </div>
</main>
<!--Main layout-->
{% endblock %}